Updated assignment based on reviewers suggestions
bjones1/literate-programming-github-fall-2024 pull request #13
Opened 2024-10-03 19:42 UTC by joshuamoorexyz

Updated assignment1.py to reflect dw2360's suggestions:

1. Added a context and objective section with URL for clarity.
2. Renamed the heading to **Objective** and moved relevant URL from the introduction.
3. Enhanced the rule description by adding "general direction towards the bomb."
4. Moved the **Helpful Links** to a new **Additional Content** section at the bottom for better flow.
5. Improved the readability of the game loop explanation, splitting complex sentences.
6. Standardized punctuation and style for uniformity across comments.
7. Reduced extra spaces to maintain consistency in code structure.

2024-10-08 18:28 UTC, bjones1 requested changes

2024-10-08 18:28 UTC, bjones1 commented on ShadowOfTheKnight-jjm702/assignment1-1.py
>  xmin, xmax, ymin, ymax = 0, w - 1, 0, h - 1
Expand to individual assignments and explain values (range is 0...w or h - 1).

2024-10-08 18:28 UTC, bjones1 commented on ShadowOfTheKnight-jjm702/assignment1-1.py
> +    # #### Update Batman's position to the middle of the new search area
Add a note on the use of `//` vs `/` and why this matters.

2024-10-14 00:48 UTC, joshuamoorexyz commented
I have added a commit addressing the requested changes. In the commit message i have detailed the specific changes made. @bjones1 Could you please review and merge if the issues have been resolved? Thanks!

2024-10-14 20:56 UTC, bjones1 approved these changes

2024-10-14 20:56 UTC, merged