Davenport Hill III - Intro to Git Assignment 10/7
bjones1/literate-programming-github-fall-2024 pull request #17
Opened 2024-10-03 22:11 UTC by dh2540

I changed my code based on my partner Cole's suggestion. Here is the advice I didn't take and the reasons.
1. CAG: I would personally add a space between each doc block and the code, but that is personal preference
Personally, having a line between the code and comments would ruin the immersion of the program. I think it is better to have no blank lines during comment to code transitions. 
2. CAG: I Think the program in the IDE and in Codechat both read very well. I might would consider adding a resources section at the bottom but that again is just preference. The main change I would make would be to put your code into the given code and present it as one cohesive program.
I added a resource section at the bottom, which was a pleasant call on him. This will help any regular person understand certain parts of my code more. The part that I disagreed with was putting my code with the given code. I did not make all of this code. That is why I made that distinction.

2024-10-07 20:07 UTC, bjones1 requested changes

2024-10-07 20:07 UTC, bjones1 commented on 2nd commit.txt
> +2nd commit to new branch
Remove all these misc files.

2024-10-07 20:07 UTC, bjones1 commented on thorgame/dh2540/The Power of Thor.cpp
> +        // Write an action using cout. DON'T FORGET THE "<< endl" To debug: cerr
This doesn't fit the rest of the comment you made -- remove or revise. I assume it was provided by the codingame site?

2024-10-07 20:07 UTC, bjones1 commented on thorgame/dh2540/The Power of Thor.cpp
> +// Helpful Links
Make this a numbered or bulleted list.

2024-10-08 19:19 UTC, dh2540 commented
I made all the changes you wanted. I got rid of the comments the CodinGame site provided, made a list for the website, etc.

2024-10-14 21:00 UTC, bjones1 approved these changes

2024-10-14 21:00 UTC, merged