all655 - Code Review Changed Completed
bjones1/literate-programming-github-fall-2024 pull request #21
Opened 2024-10-07 16:38 UTC by all655

Hey, I made the two changes that Ethan suggested: a spacing error with the code blocks and a grammar error.

2024-10-07 19:51 UTC, bjones1 requested changes

2024-10-07 19:51 UTC, bjones1 commented on ESD109-Shadowsedit/ShadowsOfTheKnight_all655.cpp
> +// # Assignment: Introduction to the CodeChat Editor
Place this in the correct directory: name of the game/netid/filename.cpp.

2024-10-07 19:51 UTC, bjones1 commented on ESD109-Shadowsedit/ShadowsOfTheKnight_all655.cpp
> +//
Too much empty space -- use just 1 line between paragraphs.

2024-10-07 19:51 UTC, bjones1 commented on ESD109-Shadowsedit/ShadowsOfTheKnight_all655.cpp
> +    int w; // width of the building.
Put comments on the preceeding line, so the CodeChat Editor will display them as a doc block.

2024-10-13 21:28 UTC, all655 commented
Due to an error that I experienced with making changes to the directory format, I have submitted a separate pull request (#37) that addressed your change suggestions. 

Sorry for the inconvenience.

2024-10-13 21:28 UTC, closed without merging