new code after review (Introduction to GitHub)
bjones1/literate-programming-github-fall-2024 pull request #25
Opened 2024-10-07 18:34 UTC by williamaguessy

I revised my code based on my classmate's suggestions.

2024-10-07 19:37 UTC, bjones1 requested changes

2024-10-07 19:37 UTC, bjones1 commented on Code review for waa94/codingame-1.c
> +
Put a `//` for empty lines between comments.

2024-10-07 19:37 UTC, bjones1 commented on Code review for waa94/codingame-1.c
> +// **Here is the second version of my code following the review :** I have added
Good, but remove this from your code -- it belong in the pull request discussion area.

2024-10-07 19:37 UTC, bjones1 commented on Code review for waa94/codingame-1.c
> +
Extra blank line.

2024-10-07 22:49 UTC, williamaguessy commented
I have revised my code based on your recommendations. Should I submit another pull request?

2024-10-13 16:39 UTC, williamaguessy commented
My Pull request is ready for review.

2024-10-14 20:56 UTC, merged