Dw2360-3 Introduction to Github assignment
bjones1/literate-programming-github-fall-2024 pull request #34
Opened 2024-10-08 04:59 UTC by dw2360

Introduction to GitHub assignment changes based on JJm's comments.

2024-10-08 18:31 UTC, bjones1 requested changes

2024-10-08 18:31 UTC, bjones1 commented on .vscode/c_cpp_properties.json
> +{
Delete all these files from your PR.

2024-10-08 18:31 UTC, bjones1 commented on thorgame/dw2360/power_of_thor.py
> +    if initial_ty < light_y and initial_tx < light_x:
This is an incomplete solution -- it works, but doesn't handle moving in directions other than SE, SW, W. Add cases for the other directions for completeness.

2024-10-15 14:43 UTC, bjones1 commented
I don't see any updates to this PR.

2024-10-16 21:15 UTC, dw2360 commented
Ready to Review.

2024-10-16 21:17 UTC, merged