TheDescent/Esd109
bjones1/literate-programming-github-fall-2024 pull request #42
Opened 2024-10-15 14:06 UTC by Ethan-Dav109

Intro to Github Assignment

2024-10-15 14:55 UTC, bjones1 requested changes

2024-10-15 21:24 UTC, bjones1 requested changes

2024-10-15 21:24 UTC, bjones1 commented on TheDescent/esd109/The DescentESD109_updated.py
> +# # Ethan Davis ESD109 The Descent CodeChat Editor
What is this? I want just one code file with the solution, not two.

2024-10-15 22:34 UTC, Ethan-Dav109 commented
Updated it, I do not know what in the world those random numbers and symbols are, they look like they are being added in while it transfers. I removed the second file and updated the first one.
________________________________
From: Bryan A. Jones ***@***.***>
Sent: Tuesday, October 15, 2024 4:24 PM
To: bjones1/literate-programming-github-fall-2024 ***@***.***>
Cc: Davis, Ethan ***@***.***>; Author ***@***.***>
Subject: Re: [bjones1/literate-programming-github-fall-2024] TheDescent/Esd109 (PR #42)


@bjones1 requested changes on this pull request.

________________________________

In TheDescent/esd109/The DescentESD109_updated.py<https://github.com/bjones1/literate-programming-github-fall-2024/pull/42#discussion_r1802036959>:

> @@ -0,0 +1,94 @@
+# # Ethan Davis ESD109 The Descent CodeChat Editor


What is this? I want just one code file with the solution, not two.

—
Reply to this email directly, view it on GitHub<https://github.com/bjones1/literate-programming-github-fall-2024/pull/42#pullrequestreview-2370730232>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BK2QZ65IBS4EUDDS5NWS6M3Z3WB2TAVCNFSM6AAAAABP7H7QRCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZQG4ZTAMRTGI>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-16 21:21 UTC, bjones1 commented on TheDescent/esd109/The DescentESD109.py
> +# <span style="background-color: #2dc26b;">esd109:</span> Thank you for this
I still see these in the file...

2024-10-16 21:22 UTC, bjones1 commented on TheDescent/esd109/The DescentESD109_updated.py
> +# # Ethan Davis ESD109 The Descent CodeChat Editor
This looks like you resolved it -- click the "Resolve conversation" below so you can keep track of what's done and what still needs doing.

2024-10-18 19:46 UTC, merged